### PR TITLE
RF - Check for SCIPY_15_PLUS at module level instead of inside function.

### PR DESCRIPTION
**Pull request by MrBago**
Not sure it matters, but putting the if statement in the module seems cleaner to me than putting it inside the function.

### CODE REVIEW

**Comment by arokem** [comment]
I think you need to rebase on top of my PR - I forgot to add back the import and got that in a subsequent commit.

**Comment by MrBago** [comment]
I think it's already on top of your branch. I don't understand the appveyor error, lets see what travis says.

**Comment by arokem** [comment]
Yikes. Appveyor SHOULD NOT be there. I am not sure how that leaked into
this. Probably my fault... Looking into it, but I have to jet in less than
20 minutes, so I might not finish this today...

**Comment by arokem** [comment]
Oh - that's probably because when experimenting with Appveyor I turned it
on for my fork, and since you are PRing against that, it gets tested that
way. No worries, I think. Feel free to ignore.

I think you still need a:

    from scipy.special import sph_harm

Somewhere in that module

**Comment by arokem** [comment]
OK - I see now. You do have it. Ignore everything I just said. Merging this
into my PR.

**Pull request merged**
